### ISSUE TITLE
ERROR: This mode not supported.

### ISSUE THREAD

**Issue by Anonymoser** [Perfare/Il2CppDumper#59]
Select Mode: 1.Manual 2.Auto 3.Auto(Advanced) 4.Auto(Plus) 5.Auto(Symbol)
Initializing il2cpp file...
Searching...
ERROR: This mode not supported.
Exception of type 'System.Exception' was thrown.
   at Il2CppDumper.Program.Main(String[] args) in C:\projects\il2cppdumper\Il2Cp
pDumper\Program.cs:line 110

ERROR: Can't use this mode to process file, try another mode.
   at Il2CppDumper.Program.Main(String[] args) in C:\projects\il2cppdumper\Il2Cp
pDumper\Program.cs:line 116
Press any key to exit...

How this have to work ?

**Comment by Anonymoser** [comment]
Files

GameAssembly.dll : http://www.mediafire.com/file/a6b0lmgdda839ix/GameAssembly.dll/file
global-metadata.dat : http://www.mediafire.com/file/r0go8ss6yr8zsbv/global-metadata.dat/file

do this for me and you will be did my wish from long time :)

**Comment by Anonymoser** [comment]
why you closed it ?

**Comment by Perfare** [comment]
I fixed a bug on this file, so I closed it.

**Comment by Anonymoser** [comment]
Unfortunately still dont work for me
did you updated the releases ?
please ?

**Comment by Perfare** [comment]
> **_ERROR: Can't use this mode to process file, try another mode._**
at Il2CppDumper.Program.Main(String[] args) in C:\projects\il2cppdumper\Il2Cp
pDumper\Program.cs:line 116
Press any key to exit...

[README.md](https://github.com/Perfare/Il2CppDumper/blob/master/README.md#error-cant-use-this-mode-to-process-file-try-another-mode)

**Comment by Anonymoser** [comment]
YOU : (I fixed a bug on this file, so I closed it.)
ok maybe i have problem
but can you send to me the output-file please ?

**Comment by Trolino** [comment]
im lost, how did you fixed the error?

**Comment by jawadahmeddogar** [comment]
why methods implementation in not decompiled...am i missing something or methods are not decompiles...??
